import { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import fs from "fs";
import path from "path";
import { createApiClient, formatApiError } from "../utils/api";
import { requireToken, requireProjectConfig } from "../utils/config";

export const pullCommand = new Command("pull")
  .description("Pull environment variables from envsync")
  .option("-e, --env <environment>", "Environment to pull from")
  .option("-o, --output <file>", "Output file", ".env")
  .option("--no-overwrite", "Skip if .env already exists")
  .action(async (options) => {
    requireToken();
    const config = requireProjectConfig();

    const env = (options.env as string | undefined) ?? config.environment;
    const outputFile = options.output as string;
    const outputPath = path.resolve(process.cwd(), outputFile);

    if (!options.overwrite && fs.existsSync(outputPath)) {
      console.log(chalk.yellow(`⚠️  ${outputFile} already exists. Use --overwrite to replace it.`));
      process.exit(0);
    }

    const spinner = ora(`Pulling ${chalk.bold(env)} variables for ${chalk.bold(config.project)}...`).start();

    try {
      const api = createApiClient();
      const { data } = await api.get(
        `/projects/${config.project}/environments/${env}/variables/export`
      );

      const variables: Record<string, string> = data.variables;
      const keys = Object.keys(variables);

      if (keys.length === 0) {
        spinner.warn(chalk.yellow("No variables found for this environment."));
        return;
      }

      // Build .env file content
      const lines = [
        `# Generated by envsync`,
        `# Project: ${config.project}  Environment: ${env}`,
        `# ${new Date().toISOString()}`,
        ``,
        ...keys.map((key) => `${key}=${formatEnvValue(variables[key])}`),
        ``,
      ];

      fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");

      spinner.succeed(
        chalk.green(`Pulled ${chalk.bold(keys.length)} variables → ${chalk.bold(outputFile)}`)
      );

      // Print the keys (not values) so the dev can see what was pulled
      console.log();
      keys.forEach((key) => {
        console.log(`  ${chalk.cyan("·")} ${key}`);
      });
      console.log();
    } catch (err) {
      spinner.fail(chalk.red(`Pull failed: ${formatApiError(err)}`));
      process.exit(1);
    }
  });

function formatEnvValue(value: string): string {
  // Quote values that contain spaces or special characters
  if (/[\s"'\\#]/.test(value)) {
    return `"${value.replace(/"/g, '\\"')}"`;
  }
  return value;
}
